"""Add Trainee model

Revision ID: 063384b146fa
Revises: 8f892e98f4e1
Create Date: 2025-07-02 13:35:38.024804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063384b146fa'
down_revision = '8f892e98f4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['trainer_unit_id'], ['trainer_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainee')
    # ### end Alembic commands ###
