"""Add workorder_id to JobInfo

Revision ID: 40b7925eed45
Revises: 434f01a34154
Create Date: 2025-07-15 18:13:51.036477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b7925eed45'
down_revision = '434f01a34154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workorder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_job_info_workorder', 'workorder_template', ['workorder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workorder_id')

    # ### end Alembic commands ###
