"""Create trainee table

Revision ID: 434f01a34154
Revises: af49898c3999
Create Date: 2025-07-02 16:13:58.088797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434f01a34154'
down_revision = 'af49898c3999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['trainer_unit_id'], ['trainer_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainee')
    # ### end Alembic commands ###
