"""Add year field to JobInfo

Revision ID: 492677828ea9
Revises: 
Create Date: 2025-06-27 19:47:50.817239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492677828ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workorder_template')
    op.drop_table('job_info')
    op.drop_table('subjective_feature')
    op.drop_table('dimensional_feature')
    op.drop_table('job_item')
    op.drop_table('user')
    op.drop_table('attitude_feature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attitude_feature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=2), nullable=True),
    sa.Column('trait', sa.VARCHAR(length=100), nullable=True),
    sa.Column('marks', sa.INTEGER(), nullable=True),
    sa.Column('workorder_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['workorder_id'], ['workorder_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimensional_feature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=1), nullable=True),
    sa.Column('size', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marks', sa.INTEGER(), nullable=True),
    sa.Column('workorder_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['workorder_id'], ['workorder_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjective_feature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=1), nullable=True),
    sa.Column('operation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('marks', sa.INTEGER(), nullable=True),
    sa.Column('workorder_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['workorder_id'], ['workorder_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('aim', sa.TEXT(), nullable=False),
    sa.Column('material', sa.VARCHAR(length=200), nullable=True),
    sa.Column('stock_size', sa.VARCHAR(length=100), nullable=True),
    sa.Column('time', sa.FLOAT(), nullable=True),
    sa.Column('instruments', sa.TEXT(), nullable=True),
    sa.Column('tools', sa.TEXT(), nullable=True),
    sa.Column('devices', sa.TEXT(), nullable=True),
    sa.Column('equipment', sa.TEXT(), nullable=True),
    sa.Column('operations', sa.TEXT(), nullable=True),
    sa.Column('other_items', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workorder_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('year', sa.VARCHAR(length=10), nullable=True),
    sa.Column('exercise_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('aim', sa.TEXT(), nullable=True),
    sa.Column('job_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('common_tolerance', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
