"""Add year_of_admission as nullable

Revision ID: 8f892e98f4e1
Revises: e327365be9d6
Create Date: 2025-07-02 09:52:58.609828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f892e98f4e1'
down_revision = 'e327365be9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_admission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer_unit', schema=None) as batch_op:
        batch_op.drop_column('year_of_admission')

    # ### end Alembic commands ###
