"""Add ex_no to JobInfo

Revision ID: e327365be9d6
Revises: 492677828ea9
Create Date: 2025-06-28 11:31:37.038263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e327365be9d6'
down_revision = '492677828ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ex_no', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_info', schema=None) as batch_op:
        batch_op.drop_column('ex_no')

    # ### end Alembic commands ###
